name: "Lint and Test"

on:
  push:
    paths:
      - lib/**
      - test/**
      - .jshintrc
      - .github/workflows/node-ci.yml
      - package.json
      - package-lock.json
  pull_request:
    paths:
      - lib/**
      - test/**
      - .jshintrc
      - .github/workflows/node-ci.yml
      - package.json
      - package-lock.json

jobs:

  build-and-test:

    name: "Build and test"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: "Set up Node"
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: "Install Node dependencies"
        run: |
          npm install

      - name: "Lint and coding style check with jshint"
        run: |
          npm run lint

      - name: "Test with mocha"
        run: |
          npm run test

